// <auto-generated />
using System;
using EuropeanParliamentTracker.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EuropeanParliamentTracker.Domain.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EuropeanParliamentTracker.Domain.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("EuropeanParliamentTracker.Domain.Models.NationalParty", b =>
                {
                    b.Property<Guid>("NationalPartyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("NationalPartyId");

                    b.ToTable("NationalPartys");
                });

            modelBuilder.Entity("EuropeanParliamentTracker.Domain.Models.Parliamentarian", b =>
                {
                    b.Property<Guid>("ParliamentarianId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CountryId");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<Guid>("NationalPartyId");

                    b.Property<string>("OfficalId");

                    b.HasKey("ParliamentarianId");

                    b.HasIndex("CountryId");

                    b.HasIndex("NationalPartyId");

                    b.ToTable("Parliamentarians");
                });

            modelBuilder.Entity("EuropeanParliamentTracker.Domain.Models.Parliamentarian", b =>
                {
                    b.HasOne("EuropeanParliamentTracker.Domain.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EuropeanParliamentTracker.Domain.Models.NationalParty", "NationlParty")
                        .WithMany()
                        .HasForeignKey("NationalPartyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
